name: "Vault-Github-Actions"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vault:
    name: 1. Vault 시크릿 조회 및 TFC 변수 설정
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Import Secrets
        id: import
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secrets/data/tfvar prefix | prefix ;
            secrets/data/tfvar height | height ;
            secrets/data/tfvar width | width;
            secrets/data/tfvar org | TF_ORGANIZATION;
            secrets/data/tfvar placeholder | placeholder;
            secrets/data/tfvar region | region ;
            terraform/creds/my-user token | TF_API_TOKEN

      - name: Setup Workspace variable
        id: set_var
        run: |
         cd /Users/jsp/code/src/tf-helper/tfh/bin/
         ./tfh pushvars -org ${{ env.TF_ORGANIZATION }} -name 'vault-gh-actions' -token ${{ env.TF_API_TOKEN }} -var 'prefix=${{ env.prefix }}' -overwrite prefix
         